baseurl = "http://www.etnacreations.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Etna Creations"
theme = "strata"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 4
publishDir = "docs"
enableRobotsTXT = true

[params]
	name = "Etna Creations"
	description = "Portfolio of the Etna Creations art lab"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/custom.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "logo.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "At the foot of the volcano"
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = "manuel"
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Manuel Badala Patane",
		]

	[params.rss]
		hide = true

	[params.about]
		hide  = false
		title = "Etna Creations"
		content = """Art and craft whose colors and shapes are inspired by the sea, the volcano, and the rich nature of our land, the island of Sicily. 
The materials used are wood, terracotta and lava stone.

The Etna Creations art lab is immersed in the enchanting nature of the island of Sicily. At the foot of the volcano, washed by the banks of the Ionian Sea is an ideal place for artistic inspiration where you can stay at "The Artist Room"."""

	[params.portfolio]
		hide  = false
		title = "Our creations"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[params.portfolio.gallery]]
			image = "fulls/vase2.jpg"
			thumb = "thumbs/vase2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/totem2.jpg"
			thumb = "thumbs/totem2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/tile.jpg"
			thumb = "thumbs/tile.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/horns.jpg"
			thumb = "thumbs/horns.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/vase.jpg"
			thumb = "thumbs/vase.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/totem.jpg"
			thumb = "thumbs/totem.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/table.jpg"
			thumb = "thumbs/table.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/vase-progress.jpg"
			thumb = "thumbs/vase-progress.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/painting.jpg"
			thumb = "thumbs/painting.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/sculpt.jpg"
			thumb = "thumbs/sculpt.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural1.jpg"
			thumb = "thumbs/mural1.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural2.jpg"
			thumb = "thumbs/mural2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural3.jpg"
			thumb = "thumbs/mural3.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural4.jpg"
			thumb = "thumbs/mural4.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural5.jpg"
			thumb = "thumbs/mural5.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural6.jpg"
			thumb = "thumbs/mural6.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/mural7.jpg"
			thumb = "thumbs/mural7.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint1.jpg"
			thumb = "thumbs/paint1.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint2.jpg"
			thumb = "thumbs/paint2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint3.jpg"
			thumb = "thumbs/paint3.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint4.jpg"
			thumb = "thumbs/paint4.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint5.jpg"
			thumb = "thumbs/paint5.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint6.jpg"
			thumb = "thumbs/paint6.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint7.jpg"
			thumb = "thumbs/paint7.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint8.jpg"
			thumb = "thumbs/paint8.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint9.jpg"
			thumb = "thumbs/paint9.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint10.jpg"
			thumb = "thumbs/paint10.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint11.jpg"
			thumb = "thumbs/paint11.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint12.jpg"
			thumb = "thumbs/paint12.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint13.jpg"
			thumb = "thumbs/paint13.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint14.jpg"
			thumb = "thumbs/paint14.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/paint15.jpg"
			thumb = "thumbs/paint15.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Visit our online shop"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"Contrada Feotto 7",
			"Fiumefreddo Sicilia",
			"Catania 95013"
		]
		phone = "+39 34-5051-2780"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "meringa92@hotmail.it"

		[params.contact.form]
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


[languages]
[languages.en]
	languageName = "English"

[languages.it]
	languageName = "Italiano"
	name = "Etna Creations"
	description = "Portfolio del laboratorio artistico Etna Creations"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	[languages.it.rss]
		hide = true

	[languages.it.sidebar]
		avatar = "logo.png"
		bio = "Ai piedi del vulcano"
		facebook = "manuel"

		copyright = [
			"&copy; Manuel Badala Patane",
		]

	[languages.it.about]
		title = "Etna Creations"
		content = """Manufatti artici e artigianali, i cui colori e forme ispirano alla nostra terra, l'isola di Sicilia.
Al mare, al vulcano, alla natura rigogliosa.
I materiali sono il legno, la terracotta e la pietra lavica.

Il laboratorio d'arte Etna Creations è immerso nella natura incantevole dell'isola, ai piedi del volcano, bagnato dalle sponde del mare Jonio, luogo ideale di inspirazione artistica, dove è possibile soggiornare presso “La stanza dell'artista”."""


	[languages.it.portfolio]
		title = "Le nostre creazioni"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[languages.it.portfolio.gallery]]
			image = "fulls/vase2.jpg"
			thumb = "thumbs/vase2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/totem2.jpg"
			thumb = "thumbs/totem2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/tile.jpg"
			thumb = "thumbs/tile.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/horns.jpg"
			thumb = "thumbs/horns.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/vase.jpg"
			thumb = "thumbs/vase.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/totem.jpg"
			thumb = "thumbs/totem.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/table.jpg"
			thumb = "thumbs/table.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/vase-progress.jpg"
			thumb = "thumbs/vase-progress.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/painting.jpg"
			thumb = "thumbs/painting.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/sculpt.jpg"
			thumb = "thumbs/sculpt.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural1.jpg"
			thumb = "thumbs/mural1.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural2.jpg"
			thumb = "thumbs/mural2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural3.jpg"
			thumb = "thumbs/mural3.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural4.jpg"
			thumb = "thumbs/mural4.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural5.jpg"
			thumb = "thumbs/mural5.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural6.jpg"
			thumb = "thumbs/mural6.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural7.jpg"
			thumb = "thumbs/mural7.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint1.jpg"
			thumb = "thumbs/paint1.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint2.jpg"
			thumb = "thumbs/paint2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint3.jpg"
			thumb = "thumbs/paint3.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint4.jpg"
			thumb = "thumbs/paint4.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint5.jpg"
			thumb = "thumbs/paint5.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint6.jpg"
			thumb = "thumbs/paint6.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint7.jpg"
			thumb = "thumbs/paint7.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint8.jpg"
			thumb = "thumbs/paint8.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint9.jpg"
			thumb = "thumbs/paint9.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint10.jpg"
			thumb = "thumbs/paint10.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint11.jpg"
			thumb = "thumbs/paint11.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint12.jpg"
			thumb = "thumbs/paint12.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint13.jpg"
			thumb = "thumbs/paint13.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint14.jpg"
			thumb = "thumbs/paint14.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint15.jpg"
			thumb = "thumbs/paint15.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[languages.it.recentposts]
		title = "Visita il nostro negozio online"

	[languages.it.contact]
		title = "Entra in contatto"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."
		email = "meringa92@hotmail.it"
		address = [
			"Contrada Feotto 7",
			"Fiumefreddo Sicilia",
			"Catania 95013"
		]
		phone = "+39 34-5051-2780"

		[languages.it.contact.form]
			name = "Nome"
			email = "E-mail"
			message = "Messaggio"
			submit = "Invia messaggio"