baseurl = "https://etnacreations.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Etna Creations"
theme = "strata"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 4
publishDir = "docs"
enableRobotsTXT = true

[params]
	name = "Etna Creations"
	description = "Portfolio of the Etna Creations art lab"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/custom.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "logo.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = ""
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Manuel Badala Patane",
		]

	[params.rss]
		hide = true

	[params.about]
		hide  = false
		title = "Etna Creations"
		content = """Etna Creations art lab is the project of Manuel Badala Patane and Antonella Micalizzi. We produce sculptures as well as profressional makeup and interior or exterior murals.

Art and craft whose shape and color is inspired by the sea, the volcano, and the rich nature of our land, the island of Sicily. 
The materials used are wood, terracotta and lava stone.

The Etna Creations art lab is immersed in the enchanting nature of the island of Sicily. At the foot of the volcano, washed by the banks of the Ionian Sea is an ideal place for artistic inspiration."""


	[params.portfolio]
		hide  = false
		title = "Our creations"

		[[params.portfolio.gallery]]
			image = "fulls/vase2.jpg"
			thumb = "thumbs/vase2.jpg"
			title = "Hand-painted terracotta vase."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/totem2.jpg"
			thumb = "thumbs/totem2.jpg"
			title = "The old man in cypress."
			description = "Cypress wood sculpture."

		[[params.portfolio.gallery]]
			image = "fulls/tile.jpg"
			thumb = "thumbs/tile.jpg"
			title = "Hand-painted tile."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/horns.jpg"
			thumb = "thumbs/horns.jpg"
			title = "Ox horn on wood."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/vase.jpg"
			thumb = "thumbs/vase.jpg"
			title = "Terracotta vase: back."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/totem.jpg"
			thumb = "thumbs/totem.jpg"
			title = "The old man in cypress: front."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/table.jpg"
			thumb = "thumbs/table.jpg"
			title = "Coffee table in solid cypress."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/vase-progress.jpg"
			thumb = "thumbs/vase-progress.jpg"
			title = "A work in progress."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/painting.jpg"
			thumb = "thumbs/painting.jpg"
			title = "A work in progress."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/sculpt.jpg"
			thumb = "thumbs/sculpt.jpg"
			title = "A work in progress."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/mural1.jpg"
			thumb = "thumbs/mural1.jpg"
			title = "Mural."
			description = "Portrait."

		[[params.portfolio.gallery]]
			image = "fulls/mural2.jpg"
			thumb = "thumbs/mural2.jpg"
			title = "Mural."
			description = "Sports bar decoration."

		[[params.portfolio.gallery]]
			image = "fulls/mural3.jpg"
			thumb = "thumbs/mural3.jpg"
			title = "Mural."
			description = "Childrens room."

		[[params.portfolio.gallery]]
			image = "fulls/mural4.jpg"
			thumb = "thumbs/mural4.jpg"
			title = "Mural."
			description = "Shop decoration."

		[[params.portfolio.gallery]]
			image = "fulls/mural5.jpg"
			thumb = "thumbs/mural5.jpg"
			title = "Mural."
			description = "Interior decoration."

		[[params.portfolio.gallery]]
			image = "fulls/mural6.jpg"
			thumb = "thumbs/mural6.jpg"
			title = "Mural."
			description = "Interior decoration."

		[[params.portfolio.gallery]]
			image = "fulls/mural7.jpg"
			thumb = "thumbs/mural7.jpg"
			title = "Mural."
			description = "Sports bar decoration."

		[[params.portfolio.gallery]]
			image = "fulls/paint1.jpg"
			thumb = "thumbs/paint1.jpg"
			title = "Brides makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint2.jpg"
			thumb = "thumbs/paint2.jpg"
			title = "Fantasy makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint3.jpg"
			thumb = "thumbs/paint3.jpg"
			title = "Fantasy makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint4.jpg"
			thumb = "thumbs/paint4.jpg"
			title = "Fantasy makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint5.jpg"
			thumb = "thumbs/paint5.jpg"
			title = "Body painting."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint6.jpg"
			thumb = "thumbs/paint6.jpg"
			title = "Makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint7.jpg"
			thumb = "thumbs/paint7.jpg"
			title = "The Siren"
			description = "Clay sculpture."

		[[params.portfolio.gallery]]
			image = "fulls/paint8.jpg"
			thumb = "thumbs/paint8.jpg"
			title = "The Siren"
			description = "Clay sculpture."

		[[params.portfolio.gallery]]
			image = "fulls/paint9.jpg"
			thumb = "thumbs/paint9.jpg"
			title = "Makeup."
			description = "Carmen Consoli concert."

		[[params.portfolio.gallery]]
			image = "fulls/paint10.jpg"
			thumb = "thumbs/paint10.jpg"
			title = "Fantasy makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint11.jpg"
			thumb = "thumbs/paint11.jpg"
			title = "Makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint12.jpg"
			thumb = "thumbs/paint12.jpg"
			title = "Makeup."
			description = ""

		[[params.portfolio.gallery]]
			image = "fulls/paint13.jpg"
			thumb = "thumbs/paint13.jpg"
			title = "Makeup."
			description = "Makeup in progress."

		[[params.portfolio.gallery]]
			image = "fulls/paint14.jpg"
			thumb = "thumbs/paint14.jpg"
			title = "Makeup."
			description = "Makeup in progress."

		[[params.portfolio.gallery]]
			image = "fulls/paint15.jpg"
			thumb = "thumbs/paint15.jpg"
			title = "Fantasy makeup."
			description = "Makeup in progress."
	[params.recentposts]
		hide  = true
		title = "Visit our online shop"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Write or call for more information on custom sculptures, makeup or murals!"

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "37.772947, 15.225001"
		address = [
			"Contrada Feotto 7",
			"Fiumefreddo di Sicilia",
			"Catania 95013"
		]
		phone = "+39 34-5051-2780"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "meringa92@hotmail.it"

		[params.contact.form]
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


[languages]
[languages.en]
	languageName = "English"

[languages.it]
	languageName = "Italiano"
	name = "Etna Creations"
	description = "Portfolio del laboratorio artistico Etna Creations"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	[languages.it.rss]
		hide = true

	[languages.it.sidebar]
		avatar = "logo.png"
		bio = ""

		copyright = [
			"&copy; Manuel Badala Patane",
		]

	[languages.it.about]
		title = "Etna Creations"
		content = """Etna Creations art lab è il progetto di Manuel Badala Patane e Antonella Micalizzi. Produciamo sculture, Make-up proferionali e murales interni o esterni.

Manufatti artistici e artigianali, i cui colori e forme ispirano alla nostra terra, l'isola di Sicilia.
Al mare, al vulcano, alla natura rigogliosa.
I materiali sono il legno, la terracotta e la pietra lavica.

Il laboratorio d'arte Etna Creations è immerso nella natura incantevole dell'isola, ai piedi del vulcano, bagnato dalle sponde del mare Jonio, luogo ideale di ispirazione artistica."""


	[languages.it.portfolio]
		title = "Le nostre creazioni"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[languages.it.portfolio.gallery]]
			image = "fulls/vase2.jpg"
			thumb = "thumbs/vase2.jpg"
			title = "Giara in terracotta dipinta a mano."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/totem2.jpg"
			thumb = "thumbs/totem2.jpg"
			title = "Il vecchio cipresso."
			description = "Scultura in legno di cipresso."

		[[languages.it.portfolio.gallery]]
			image = "fulls/tile.jpg"
			thumb = "thumbs/tile.jpg"
			title = "Vecchia tegola dipinta a mano."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/horns.jpg"
			thumb = "thumbs/horns.jpg"
			title = "Corna di bue su legno."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/vase.jpg"
			thumb = "thumbs/vase.jpg"
			title = "Giara in terracotta: retro."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/totem.jpg"
			thumb = "thumbs/totem.jpg"
			title = "Il vecchio cipresso: frontale."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/table.jpg"
			thumb = "thumbs/table.jpg"
			title = "Tavolo basso in legno massello di cipresso."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/vase-progress.jpg"
			thumb = "thumbs/vase-progress.jpg"
			title = "In fase di realizzazione."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/painting.jpg"
			thumb = "thumbs/painting.jpg"
			title = "In fase di realizzazione."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/sculpt.jpg"
			thumb = "thumbs/sculpt.jpg"
			title = "In fase di realizzazione."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural1.jpg"
			thumb = "thumbs/mural1.jpg"
			title = "Murales."
			description = "Ritratto."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural2.jpg"
			thumb = "thumbs/mural2.jpg"
			title = "Murales."
			description = "Decorazione centro scommesse."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural3.jpg"
			thumb = "thumbs/mural3.jpg"
			title = "Murales."
			description = "Camera per bambini."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural4.jpg"
			thumb = "thumbs/mural4.jpg"
			title = "Murales."
			description = "Decorazione negozio."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural5.jpg"
			thumb = "thumbs/mural5.jpg"
			title = "Murales."
			description = "Decorazione interni."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural6.jpg"
			thumb = "thumbs/mural6.jpg"
			title = "Murales."
			description = "Decorazione interni."

		[[languages.it.portfolio.gallery]]
			image = "fulls/mural7.jpg"
			thumb = "thumbs/mural7.jpg"
			title = "Murales."
			description = "Decorazione centro scommesse."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint1.jpg"
			thumb = "thumbs/paint1.jpg"
			title = "Make-up sposa."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint2.jpg"
			thumb = "thumbs/paint2.jpg"
			title = "Make-up fantasy."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint3.jpg"
			thumb = "thumbs/paint3.jpg"
			title = "Make-up fantasy."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint4.jpg"
			thumb = "thumbs/paint4.jpg"
			title = "Make-up fantasy."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint5.jpg"
			thumb = "thumbs/paint5.jpg"
			title = "Body painting."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint6.jpg"
			thumb = "thumbs/paint6.jpg"
			title = "Make-up."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint7.jpg"
			thumb = "thumbs/paint7.jpg"
			title = "Sirena."
			description = "Scultura in argilla."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint8.jpg"
			thumb = "thumbs/paint8.jpg"
			title = "Sirena."
			description = "Scultura in argilla."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint9.jpg"
			thumb = "thumbs/paint9.jpg"
			title = "Make-up."
			description = "Concerto Carmen Consoli."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint10.jpg"
			thumb = "thumbs/paint10.jpg"
			title = "Make-up fantasy."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint11.jpg"
			thumb = "thumbs/paint11.jpg"
			title = "Make-up."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint12.jpg"
			thumb = "thumbs/paint12.jpg"
			title = "Make-up."
			description = ""

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint13.jpg"
			thumb = "thumbs/paint13.jpg"
			title = "Make-up."
			description = "Preparazione."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint14.jpg"
			thumb = "thumbs/paint14.jpg"
			title = "Make-up."
			description = "Preparazione."

		[[languages.it.portfolio.gallery]]
			image = "fulls/paint15.jpg"
			thumb = "thumbs/paint15.jpg"
			title = "Make-up fantasy."
			description = "preparazione."


	[languages.it.recentposts]
		hide = true
		title = "Visita il nostro negozio online"

	[languages.it.contact]
		title = "Entra in contatto"
		content = "Scrivere o richiedere ulteriori informazioni su scultura personalizzata, Make-up o murales!"
		email = "meringa92@hotmail.it"
		gmaps_address = "37.772947, 15.225001"
		address = [
			"Contrada Feotto 7",
			"Fiumefreddo di Sicilia",
			"Catania 95013"
		]
		phone = "+39 34-5051-2780"

		[languages.it.contact.form]
			name = "Nome"
			email = "E-mail"
			message = "Messaggio"
			submit = "Invia messaggio"