baseurl = "http://www.etnacreations.com/"
languageCode = "en-us"
title = "Etna Creations"
theme = "strata"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 4
publishDir = "docs"
enableRobotsTXT = true

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Etna Creations"
	description = "Portfolio of Manual Badala art and creations"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/custom.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "logo.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Realized at the<br> feet of Mount Etna"
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = "manuel"
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Manuel Badala",
		]

	[params.rss]
		hide = true

	[params.about]
		hide  = false
		title = "Etna Creations"
		content = ""


	[params.portfolio]
		hide  = false
		title = "Our creations"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like

		[[params.portfolio.gallery]]
			image = "fulls/vase2.jpg"
			thumb = "thumbs/vase2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/totem2.jpg"
			thumb = "thumbs/totem2.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/tile.jpg"
			thumb = "thumbs/tile.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/horns.jpg"
			thumb = "thumbs/horns.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/vase.jpg"
			thumb = "thumbs/vase.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/totem.jpg"
			thumb = "thumbs/totem.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/table.jpg"
			thumb = "thumbs/table.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/vase-progress.jpg"
			thumb = "thumbs/vase-progress.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/painting.jpg"
			thumb = "thumbs/painting.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.recentposts]
		hide  = false
		title = "Visit our online store"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"Contrada Feotto 7",
			"Fiumefreddo Sicilia",
			"Catania 95013"
		]
		phone = "+39-34-5051-2780"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "meringa92@hotmail.it"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
# [[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10

# [[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 0
